// GENERATED by scripts/gen-media-version.mjs — do not edit by hand.
// Content hash of the hero media, appended to its URLs so a replaced file
// never collides with a cached copy of the old one.
export const heroMediaVersion = "9aa096ed0b0bcb01";
